AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'coverage/**/*'
    - 'allure-results/**/*'
    - 'reports/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'spec/**/*'
    - 'features/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'features/**/*'
    - 'cucumber.yml'

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'spec/**/*'
    - 'features/**/*'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'
    - 'features/**/*'

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets
